### PR TITLE
correct typo in error msg if user does not exist

### PR DESCRIPTION
**Pull request by hmenager**

### CODE REVIEW

**Comment by hmenager** [comment]
@hansioan this is a very very minor correction but I  do not know your git workflow, so I will let you decide if and how to merge this :smile:

**Comment by hansioan** [comment]
@hmenager Please make the PR to merge in the develop branch. 
For now I would only like to have develop merge into master.

**Comment by hmenager** [comment]
will do @hansioan

**Comment by hmenager** [comment]
done ;)

**Pull request merged**
