### PR TITLE
conforms to 0.6-draft bioschemas ComputationalTool profile

### PR DESCRIPTION
**Pull request by albangaignard**
Main modifications : 
 - Use of FormalParameter types for inputs and outputs
 - use of `dct:conformsTo` to refer to the Bioschemas profile version

### CODE REVIEW

**Comment by hansioan** [comment]
@albangaignard 
Thanks for the PR
Let me also test the branch locally and make sure everything runs ok and then I will approve it asap

Hans

**Comment by hansioan** [comment]
@albangaignard 
I looked at the branch and it works fine.

I've found one (annoying in the future) issue though, which is not really related to the point of this PR, but perhaps we can also fix it here if it's not too hard, otherwise we do it later.
The issue is that the order of different items in an array (e.g. EDAM terms, tool-types ) changes if the page is refresh.
In fact, if you refresh enough times even the immediate elements in the `graph` list switch around.
This might be an issue with diffs later on (i.e. ecosystem)

Go to:
https://bio.tools/api/blast?format=jsonld

and keep refreshing the page to see them switch around.

If you refresh for regular json:
https://bio.tools/api/blast?format=json
https://bio.tools/api/blast?format=api
the ordering is kept so I assume there is something in wrong in the conversion to jsonld code...

I don't have strong opinions regarding fixing it in this PR or in a different one. What do you think?

**Review by hansioan — APPROVED** [review]
OK, except the issue about the ordering which I'm not sure if it should be addressed here or not

**Comment by albangaignard** [comment]
Ok, noted for the order which is not preserved in the JSON-LD serialization. In RDF graphs, the order of triples is not important. See  https://www.w3.org/TR/json-ld11-streaming/#triple-ordering-importance for ordering strategies.

**Review by hansioan — APPROVED** [review]

**Pull request merged**
